### PR TITLE
add test for deadlines

### PR DESCRIPTION
**Pull request by vyzo**
seems to be broken...

### CODE REVIEW

**Comment by Stebalien** [comment]
Deadlock?

**Comment by vyzo** [comment]
Not sure what it is, the `AwaitEOF` goroutines are stuck in `waitForData` apparently without a deadline.

**Comment by Stebalien** [comment]
Can we figure out what's actually happening? The code looks correct.

**Comment by vyzo** [comment]
I agree that the code looks correct, so this is a little mystifying...

**Comment by vyzo** [comment]
Oh I think I know what's happening: we set the handshake deadline in the stream, which can then time out, killing the `Close` `sendMsg`!
It's a bug in the relay code, the deadline needs to be reset before attempting to `handleError`.

**Comment by vyzo** [comment]
No wait, close is not sent with the deadline.

**Comment by vyzo** [comment]
ah, it is the bug indeed in the `error` message is never sent due to the deadline being exceeded, which results in the initiating peer never responding.

**Comment by vyzo** [comment]
no wait, the deadline is on the other side of the hop.

**Comment by vyzo** [comment]
trying to debug the issue: restored deadline setting checks and added error logs when not setting the read deadlines.

**Comment by vyzo** [comment]
It's full of these:
```
May 23 10:19:13 localhost relay.sh[18486]: 10:19:13.809 ERROR     mplex: not setting deadline; stream is closed mstream.go:255
```

**Comment by vyzo** [comment]
so the stream is already marked closed, failing to set the deadline in `AwaitEOF`.

**Comment by vyzo** [comment]
the more pertinent question is why `waitForData` doesn't return immediately, which would be the bug.

**Comment by vyzo** [comment]
I don't understand how this is happening, we always close either `reset` or `dataIn` when we set `closedRemote = true`...

**Comment by vyzo** [comment]
Added assertion in https://github.com/libp2p/go-mplex/pull/60/commits/c2ceeb7e9358ae2d05a58f610e1e0739ed7c81e4 to test for the impossible condition.

**Comment by vyzo** [comment]
it's not triggering, so that was possibly a red herring...

**Comment by vyzo** [comment]
I can't seem to reproduce the issue; I don't know what happened.

At any rate, this adds a test for deadlines that was missing.

**Pull request merged**
