### PR TITLE
downgrade Error log to Warning

### PR DESCRIPTION
**Pull request by vyzo**
It log spams in relays

### CODE REVIEW

**Comment by whyrusleeping** [comment]
Wait... Why are we seeing this at all? This would imply a broken implementation

**Comment by vyzo** [comment]
Ok, let's punt on downgrading and hunt for a bug instead.

**Comment by vyzo** [comment]
Ok, something must be done about this log, regardless of bug. It filled the disk in the mplex relay.

**Comment by vyzo** [comment]
I made it a Warning.

**Comment by Stebalien** [comment]
Could be https://github.com/ipfs/go-ipfs/issues/6197 causing a concurrent write?

**Comment by Stebalien** [comment]
Could also be a bug in js?

**Comment by Stebalien** [comment]
Ah, no. It's a cleanup race. We set `closedRemote` when closing the connection or resetting the stream.

**Comment by vyzo** [comment]
Probably because of stream resets.

**Pull request merged**
